name: SpigotLib
author: gyuriX
version: '10.0'
api-version: '1.13'
main: gyurix.spigotlib.Main
loadbefore: [ProtocolLib,ProtocolSupport]
softdepend: [LilyPad-Connect,ViaVersion,Vault,Essentials,PlaceholderAPI]
commands:
  spigotlib:
    aliases: [sl]
    description: Main command